sudo: false
# Travis actually needs to have python, ruby, and nodejs installed.
# It _seems_ virtualenv is only available when the language is set to python
# When language=python it seems Travis runs this command:
# source ~/virtualenv/python2.7/bin/activate
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - shellcheck
      # For building kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - rvm default
  # Build https://github.com/SimonKagstrom/kcov (shell code coverage)
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    rm master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master
script: kcov ./coverage/ ./script/test
after_success: bash <(curl -s https://codecov.io/bash)
