#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# Validate the shell scripts
# shellcheck disable=SC2046
try shellcheck $(find ./script -not -path '*/\.*' -mindepth 1 -maxdepth 1 -type f)
